# Grid Search CV

In [25]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [26]:
import warnings
warnings.filterwarnings('ignore')

In [27]:
df = sns.load_dataset('iris')

In [28]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [29]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
X = df.drop('species', axis=1)
y = df['species']

In [32]:
# with train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [33]:
from sklearn.neighbors import KNeighborsClassifier

In [34]:
model_knn = KNeighborsClassifier(n_neighbors=5)
model_knn.fit(X_train, y_train)

KNeighborsClassifier()

In [35]:
model_knn.score(X_test, y_test)

1.0

In [36]:
from sklearn.svm import SVC

In [40]:
# model_svm = SVC(C = 30, kernel = 'rbf', gamma='auto')
model_svm = SVC(gamma='auto')
model_svm.fit(X_train, y_train)

SVC(gamma='auto')

In [41]:
model_svm.score(X_test, y_test)

1.0

# Now lets use Grid Search CV

In [39]:
# Now lets use Grid Search CV

from sklearn.model_selection import GridSearchCV

In [42]:
classifier = GridSearchCV(model_svm, {
    'C': [1, 10, 20, 30],
    'kernel': ['rbf', 'linear', 'poly', 'sigmoid']
}, cv = 5, return_train_score = False)

In [43]:
classifier.fit(X, y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30],
                         'kernel': ['rbf', 'linear', 'poly', 'sigmoid']})

In [53]:
print("Best parameters for KNN:", classifier.best_params_)
print("Best score for KNN:", classifier.best_score_)

Best parameters for KNN: {'C': 1, 'kernel': 'rbf'}
Best score for KNN: 0.9800000000000001

In [49]:
results = pd.DataFrame(classifier.cv_results_)
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.012876,0.000819,0.009481,0.002653,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.010140,0.003481,0.006906,0.002820,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.018565,0.008630,0.008219,0.003268,1,poly,"{'C': 1, 'kernel': 'poly'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,6
3,0.010698,0.004442,0.005851,0.002311,1,sigmoid,"{'C': 1, 'kernel': 'sigmoid'}",0.333333,0.100000,0.000000,0.033333,0.0,0.093333,0.125433,13
4,0.003747,0.000241,0.002639,0.000098,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
5,0.004020,0.001127,0.002686,0.000095,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.966667,1.0,0.973333,0.038873,4
6,0.010987,0.004097,0.004147,0.001131,10,poly,"{'C': 10, 'kernel': 'poly'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,6
7,0.009664,0.005152,0.007085,0.004651,10,sigmoid,"{'C': 10, 'kernel': 'sigmoid'}",0.333333,0.100000,0.000000,0.033333,0.0,0.093333,0.125433,13
8,0.004104,0.000886,0.002811,0.000168,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,5
9,0.006489,0.002674,0.004326,0.001908,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,6
10,0.018871,0.012478,0.004754,0.001993,20,poly,"{'C': 20, 'kernel': 'poly'}",0.966667,0.966667,0.900000,0.933333,1.0,0.953333,0.033993,11
11,0.011080,0.004451,0.005934,0.002123,20,sigmoid,"{'C': 20, 'kernel': 'sigmoid'}",0.333333,0.100000,0.000000,0.033333,0.0,0.093333,0.125433,13
12,0.006958,0.005319,0.005641,0.003560,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.000000,0.900000,0.933333,1.0,0.960000,0.038873,9
13,0.007127,0.003769,0.007082,0.003648,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.900000,1.0,0.960000,0.048990,9
14,0.044350,0.026751,0.008781,0.003324,30,poly,"{'C': 30, 'kernel': 'poly'}",0.966667,0.966667,0.900000,0.933333,1.0,0.953333,0.033993,11
15,0.011775,0.004865,0.006808,0.001993,30,sigmoid,"{'C': 30, 'kernel': 'sigmoid'}",0.333333,0.100000,0.000000,0.033333,0.0,0.093333,0.125433,13

In [50]:
results.head()

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.012876,0.000819,0.009481,0.002653,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.010140,0.003481,0.006906,0.002820,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.018565,0.008630,0.008219,0.003268,1,poly,"{'C': 1, 'kernel': 'poly'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
3,0.010698,0.004442,0.005851,0.002311,1,sigmoid,"{'C': 1, 'kernel': 'sigmoid'}",0.333333,0.1,0.000000,0.033333,0.0,0.093333,0.125433,13
4,0.003747,0.000241,0.002639,0.000098,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1

In [52]:
results[['param_C', 'param_kernel', 'mean_test_score']]

    param_C param_kernel  mean_test_score
0         1          rbf         0.980000
1         1       linear         0.980000
2         1         poly         0.966667
3         1      sigmoid         0.093333
4        10          rbf         0.980000
5        10       linear         0.973333
6        10         poly         0.966667
7        10      sigmoid         0.093333
8        20          rbf         0.966667
9        20       linear         0.966667
10       20         poly         0.953333
11       20      sigmoid         0.093333
12       30          rbf         0.960000
13       30       linear         0.960000
14       30         poly         0.953333
15       30      sigmoid         0.093333